### ISSUE TITLE
Compra e venda

### ISSUE THREAD

**Issue by cleitondm** [rrfaria/iqoption-bot#5]
Estou rodando para USDJPY e EURUSD 
minha duvida e o sistema vai comprar automaticamente dentro IQoption? conta demo?

**Comment by rrfaria** [comment]
Não compra não .
ele pega os dados e gera o gráfico baseado neles e quando o ml encontra uma venda ou compra, ele plota no gráfico, mas ele não compra automático só mostra o que tem que ser feito.

por padrão ele pega os dados do modo que vc já ta usando. Por exemplo se eu tiver na demo ele mostra dados da demo apesar que em questão de gráfico parece ser o mesmo não muda nada.

Ele não mostra as suas compras apenas as sugestões de comprar do ml. 

Mas esta em teste. eu não aconselho usar na conta real como indicador é apenas para fins de estudo.

O código precisa ser melhorado, se quiser contribuir pode abrir um PR explicando o que alterar e porquê fez, só pra ficar fácil de entender.

**Comment by cleitondm** [comment]
Entender melhor seu script
para adicionar a compra automatica seria tipo isso
Iq.buy(1, 1, "turbo", "sell")
Proximo essa linha!!!
                        #print("--**--** SELL ", str(float( sells[ind]))," - Lucro = US$ ", str(profit))

**Comment by rrfaria** [comment]
O script é baseado em um conteúdo que o Saulo catarino havia feito
ele tinha uma playlist de videos no youtube mas agora esta tudo privado

https://www.youtube.com/playlist?list=PLF4RJ05Br9XK8uPxKiaQC3D_8WOKYN_yB

esse script é baseado no código dele eu apenas adicionei a fonte de dados como a iqoption

eu tinha o costume de olhar os videos dele quando queria relembrar alguma coisa mas agora ta tudo privado antes estava publico.
