### ISSUE TITLE
Dependences problems

### ISSUE THREAD

**Issue by papalardo** [rrfaria/iqoption-bot#6]
#When I run ```pip install -r requirements.txt```, there was a problem:

```bash
ERROR: Could not find a version that satisfies the requirement sklearn==0.20.3 (from -r requirements.txt (line 10)) (from versions: 0.0)
ERROR: No matching distribution found for sklearn==0.20.3 (from -r requirements.txt (line 10))
```

Then I change ```sklearn==0.20.3``` to ```scikit-learn==0.21.3``` and fix it, but I dont know if this is correct.

Maybe, after fix it this way, there was another problem: 

```bash
ERROR: Could not find a version that satisfies the requirement talib==0.4.17 (from -r requirements.txt (line 12)) (from versions: 0.1.1)
ERROR: No matching distribution found for talib==0.4.17 (from -r requirements.txt (line 12))
```

```bash
❯ python --version
Python 3.7.6

❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
```

How fix it ?

**Comment by rrfaria** [comment]
Hi I don't know what is happen but I can try discover this 
And you may write question in portuguese if you want .
I put everything here in english to engage more people around the world

**Comment by papalardo** [comment]
@rrfaria acredito que as versōes dessas dependências não existem mais.. não sei exatamente, sou iniciante em python mas foi o que eu a entender.

**Comment by rrfaria** [comment]
when I developed this code I have installed all thing and after all I started organize this, so maybe some parts can be outdated or with errors ... On my machine it still working but in new install I don't know.

I'll try create new VM with this code and analyse what is happen.

talib is not been used on the project 
I was planning implement it in a future step 
you can remove this for now

talib is a library which contains a lot of trader indicators and I was planning add new indicators to try improve the model

**Comment by rrfaria** [comment]
@papalardo ta escrito errado o talib 
mas você nem precisa dela para rodar 
vc pode só remover 
ou fazer um pip install:
pip install TA-Lib

**Comment by rrfaria** [comment]
@papalardo criei um discord pra galera discutir por lá qualquer duvida se quiser dar uma olhada depois 
https://discord.gg/59Gdg6

**Comment by papalardo** [comment]
@rrfaria 

> @papalardo ta escrito errado o [talib](https://github.com/mrjbq7/ta-lib)
> mas você nem precisa dela para rodar
> vc pode só remover
> ou fazer um pip install:
> pip install TA-Lib

isso resolveu o problema. O último commit resolveu o problemas das dependences também. Obg.
